apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mahasiswa-db
  name: mahasiswa-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mahasiswa-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mahasiswa-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: db_mahasiswa_iae
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:8.0
          name: mysql-mahasiswa-db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-mahasiswa
      restartPolicy: Always
      volumes:
        - name: mysql-mahasiswa
          persistentVolumeClaim:
            claimName: mysql-mahasiswa
