apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mahasiswaservice
  name: mahasiswaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mahasiswaservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mahasiswaservice
    spec:
      containers:
        - args:
            - sh
            - -c
            - |
              php artisan migrate --force;
              apache2-foreground
          env:
            - name: DB_DATABASE
              value: db_mahasiswa_iae
            - name: DB_HOST
              value: mahasiswa-db
            - name: DB_PASSWORD
              value: root
            - name: DB_USERNAME
              value: root
            - name: QUEUE_CONNECTION
              value: database
            - name: REDIS_CLIENT
              value: predis
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: NILAI_SERVICE_URL
              value: http://nilaiservice:9071
          image: bariq47/mahasiswaservice:latest
          name: laravel-mahasiswaservice
          ports:
            - containerPort: 80
              protocol: TCP
      #     volumeMounts:
      #       - mountPath: /var/www/html
      #         name: mahasiswaservice-cm0
      #     workingDir: /var/www/html
      # restartPolicy: Always
      # volumes:
      #   - configMap:
      #       name: mahasiswaservice-cm0
      #     name: mahasiswaservice-cm0