apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-nilai
  name: mysql-nilai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
