apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nilaiservice
  name: nilaiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nilaiservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nilaiservice
    spec:
      containers:
        - args:
            - sh
            - -c
            - |
              php artisan migrate --force;
              apache2-foreground
          env:
            - name: DB_DATABASE
              value: db_nilai_iae
            - name: DB_HOST
              value: nilai-db
            - name: DB_PASSWORD
              value: root
            - name: DB_USERNAME
              value: root
            - name: QUEUE_CONNECTION
              value: database
            - name: REDIS_CLIENT
              value: predis
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MAHASISWA_SERVICE_URL
              value: http://mahasiswaservice:9070
          image: bariq47/nilaiservice:latest
          name: laravel-nilaiservice
          ports:
            - containerPort: 80
              protocol: TCP
      #     volumeMounts:
      #       - mountPath: /var/www/html
      #         name: nilaiservice-cm0
      #     workingDir: /var/www/html
      # restartPolicy: Always
      # volumes:
      #   - configMap:
      #       name: nilaiservice-cm0
      #     name: nilaiservice-cm0
