apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: phpmyadmin-nilai
  name: phpmyadmin-nilai
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin-nilai
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: phpmyadmin-nilai
    spec:
      containers:
        - env:
            - name: PMA_HOST
              value: nilai-db
            - name: PMA_PASSWORD
              value: root
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin-nilai
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
