apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: phpmyadmin-nilai
  name: phpmyadmin-nilai
spec:
  ports:
    - name: "9081"
      port: 9081
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin-nilai
  
